from shapely.geometry import Polygon
from reading_order.stubs import Candidate
from spatial.stubs import Region as StubRegion


class Region(StubRegion):
    def get_id(self) -> str: ...


class TextRegion(Region, Candidate): ...


class Document(object):
    def get_regions(self) -> {StubRegion}: ...

    def get_text_regions(self) -> {TextRegion}: ...

    def get_image_width(self) -> int: ...

    def get_image_height(self) -> int: ...

    def get_box(self) -> Polygon: ...
